# Define la versión de PHP que usará Railway
[variables]
NIXPACKS_PHP_VERSION = "8.3"

# Instala las dependencias del sistema y extensiones de PHP
[phases.setup]
nixPkgs = [
    "pkgs.php83Extensions.gd", 
    "pkgs.php83Extensions.bcmath"
]