# Archivo de configuración definitivo para Nixpacks en Railway

# Define las versiones de PHP y Node que se usarán.
[providers]
php = "8.3"
node = "20"

# Fase de Instalación (Setup): Añade las extensiones de PHP que faltaban.
[phases.setup]
nixPkgs = [
    "pkgs.php83Extensions.gd", 
    "pkgs.php83Extensions.bcmath",
    "pkgs.php83Extensions.pgsql"
]

# Fase de Construcción (Build): Instala dependencias y compila los assets.
[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev",
    "npm ci --no-optional",
    "npm run build",
    "php artisan optimize:clear"
]

# Comando de Inicio (Start): Prepara la BD y lanza el servidor.
[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan optimize && vendor/bin/heroku-php-apache2 public/"