# ===================================================
#      CONFIGURACIÓN PARA NIXPACKS
# ===================================================

[phases.setup]
aptPkgs = [
    "php8.3-gd", 
    "php8.3-bcmath"
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci",
    "npm run build",
    "php artisan optimize:clear"
]

[phases.start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan optimize && vendor/bin/heroku-php-apache2 public/"