# Archivo de configuración definitivo para Nixpacks en Railway

# 1. Define las versiones de PHP y Node.
[providers]
php = "8.3"
node = "20"

# 2. Fase de Instalación (Setup): Usa 'apt' para forzar la instalación de las extensiones.
# Este método tiene mayor prioridad y anula la lista por defecto de Railpack.
[phases.setup]
aptPkgs = [
    "php8.3-gd", 
    "php8.3-bcmath"
]

# 3. Fase de Construcción (Build): Instala dependencias y compila los assets.
[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev",
    "npm ci --no-optional",
    "npm run build",
    "php artisan optimize:clear"
]

# 4. Comando de Inicio (Start): Prepara la BD y lanza el servidor.
[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan optimize && vendor/bin/heroku-php-apache2 public/"